version: "3.7"
services:
  app:
    build:
      args:
        user: jd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: payesa
    container_name: payesa-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - payesa

  db:
    image: mysql:5.7
    container_name: payesa-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3308:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - payesa
    
  nginx:
    image: nginx:1.17-alpine
    container_name: payesa-nginx
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - payesa

networks:
  payesa:
    driver: bridge